[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

# Minimal valid redirects for Netlify functions and SPA
[[redirects]]
  from = "/api/fred-proxy"
  to = "/.netlify/functions/fred-proxy"
  status = 200
  force = true

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = ["node-fetch"]

[dev]
  framework = "#custom"
  command = "npm run dev"
  targetPort = 3000
  port = 8888 