[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

# Handle client-side routing
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "20"

[build.processing]
  skip_processing = true

[build.processing.css]
  bundle = false
  minify = false

[build.processing.js]
  bundle = false
  minify = false

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = false

[secrets]
  SECRETS_SCAN_ENABLED = true
  # Ignore build output and other necessary paths
  SECRETS_SCAN_OMIT_PATHS = [
    "node_modules/**/*",
    "dist/**/*",
    ".netlify/**/*"
  ]
  # Specify which environment variables to ignore in scanning
  SECRETS_SCAN_OMIT_KEYS = [
    "FRED_API_KEY",
    "VITE_FRED_API_KEY"
  ]

[dev]
  framework = "#custom"
  command = "npm run dev"
  targetPort = 3000
  port = 8888 