[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

# Handle client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "20"

[secrets]
  SECRETS_SCAN_ENABLED = true
  SECRETS_SCAN_OMIT_PATHS = ["node_modules/**/*"] 