[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

# Handle FRED API requests through our Netlify function
[[redirects]]
  from = "/.netlify/functions/fred-proxy"
  to = "/.netlify/functions/fred-proxy"
  status = 200
  force = true

[[redirects]]
  from = "/api/fred/*"
  to = "/.netlify/functions/fred-proxy"
  status = 200
  force = true

# Handle other API routes
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

# Handle client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "20"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["node-fetch"]

[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true

[secrets]
  SECRETS_SCAN_ENABLED = true
  # Ignore build output and other necessary paths
  SECRETS_SCAN_OMIT_PATHS = [
    "node_modules/**/*",
    "dist/**/*",
    ".netlify/**/*",
    "*.log",
    "*.lock"
  ]
  # Specify which environment variables to ignore in scanning
  SECRETS_SCAN_OMIT_KEYS = [
    "FRED_API_KEY",
    "VITE_FRED_API_KEY",
    "VITE_BLS_API_KEY",
    "VITE_EIA_API_KEY"
  ]

[dev]
  framework = "#custom"
  command = "npm run dev"
  targetPort = 3000
  port = 8888 