[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

# Configure secrets scanning
[secrets]
  scan_enabled = true
  scan_omit_paths = ["node_modules", "dist"]
  scan_omit_keys = ["VITE_METAL_PRICE_API_KEY", "FRED_API_KEY", "SUPABASE_URL", "SUPABASE_SERVICE_ROLE_KEY"]

# Ignore secrets in build output
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true

[build.processing.js]
  bundle = true
  minify = true

# Configure redirects
[[redirects]]
  from = "/api/fred-proxy"
  to = "/.netlify/functions/fred-proxy"
  status = 200
  force = true

[[redirects]]
  from = "/api/fred/*"
  to = "/.netlify/functions/fred-proxy"
  status = 200
  force = true

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Configure functions
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = ["node-fetch"]

[dev]
  framework = "#custom"
  command = "npm run dev"
  targetPort = 3000
  port = 8888
